### ISSUE TITLE
PEP 458:  Seeking Alternative Words for a Few Terms

### ISSUE THREAD

**Issue by vladimir-v-diaz** [pypa/interoperability-peps#13]
I would like to find better words for a few terms used in PEP 458.  Suggestions and feedback is appreciated.

A. Offline and Online keys

Online keys are stored on PyPI infrastructure, allow automated signing of metadata, and are easily read by attackers if PyPI is compromised.  An offline key is the opposite, and may be owned and used by PyPI administrators to sign PyPI roles (e.g., `root.json` and `targets/claimed.json`), or by developers who sign their delegated metadata (e.g., `targets/claimed/django.json`).

alternative terms:
1. off-pypi, on-pypi
2. off-site, on-site
3. managed, automated 

B. Claimed and Unclaimed roles

The `claimed` roles are managed and signed by developers.  In contrast, the `unclaimed` role is signed by PyPI administrators in an automated fashion.

alternative terms:
1. pypi-claimed, developer-claimed
2. developer-signed, pypi-signed
3. developer-managed, pypi-managed

Feedback given by `distutils-sig` community member:

"Although on the terminology front, I don't really understand what an
"online key" and an "offline key" are. My mind translates them as
"worse" and "better" from context, but that's about all. I'm not
asking for an explanation (I can look that up) but as terms being
encountered by the non-specialist, they contribute to the difficulty
in reading the proposals. If there's any better way of naming these
two types of keys, that would be accessible to the non-specialist,
that would be a great help."

"I'm not keen on the term "unclaimed". All projects on PyPI right now
are "unclaimed" by that usage, which is emphatically not what
"unclaimed" means intuitively to me. Surely "pip" is "claimed" by the
PyPA? Maybe "unverified" works as a term (as in, verifying your
account when signing up to a forum). I get the idea that unclaimed
implies there's a risk, and sure there is, but this smacks of using a
loaded term to rub people's noses in the fact that what they've been
happily using for years "isn't safe". This happens a lot with security
debates, and IMO actively discourages people from buying into the
changes."

**Comment by JustinCappos** [comment]
I tend to like off-pypi / on-pypi for online and offline keys.  We do want
to make it clear that a breach of PyPI puts those keys at risk and I feel
this term conveys it better than the others.

For claimed / unclaimed, I find developer-signed / pypi-signed to be the
most intuitive.  To me, "managed" sounds too much like editing the code and
"claimed" doesn't mean much at all.

However, it is more valuable to hear from people who haven't spent the past
few years speaking the "project lingo".  :)

**Comment by ncoghlan** [comment]
I like on-pypi/off-pypi and developer-signed/pypi-signed.

For keys, I think off-pypi effectively conveys that those keys may still be online *somewhere*, just on a far more restricted service without quite so many attack vectors as the main PyPI server. The PEP doesn't specifically care that they be offline entirely, it just cares that an attack on PyPI itself won't compromise them. Avoiding common points of attack on the PyPI service and the off-pypi keys is then the responsibility of the PyPI maintainers, and outside the scope of the PEP.

For signing, I definitely like the switch in naming emphasis to "Who are you trusting?". With the current TLS based approach, you're trusting the developer, PyPI, the TLS endpoint termination provider and the TLS CA system. With PyPI signed packages, you're trusting the developer and PyPI, while with developer signed packages you're just trusting the developer.

**Comment by dachshund** [comment]
On 7 January 2015 at 22:53, ncoghlan <notifications@github.com> wrote:

> For signing, I definitely like the switch in naming emphasis to "Who are
> you trusting?". With the current TLS based approach, you're trusting the
> developer, PyPI, the TLS endpoint termination provider and the TLS CA
> system. With PyPI signed packages, you're trusting the developer and PyPI,
> while with developer signed packages you're just trusting the developer.
>

I just wanted to add that even with developer-signed packages, you do trust
PyPI to tell you (with off-pypi, pypi-signed keys) what the right public
keys of the developers are, but that is the extent of the trust.

**Comment by ncoghlan** [comment]
True, there's still a requirement to trust the PyPI administrators (who are in effect acting as a CA for developer signing keys), just not the online PyPI service itself.

**Comment by dachshund** [comment]
On 8 January 2015 at 02:11, ncoghlan <notifications@github.com> wrote:

> True, there's still a requirement to trust the PyPI administrators (who
> are in effect acting as a CA for developer signing keys), just not the
> online PyPI service itself.
>
Yes. Good analogy :)

**Comment by vladimir-v-diaz** [comment]
The alternative terms `on-pypi`, `off-pypi`, `pypi-signed`, and `developer-signed` were added in PR https://github.com/pypa/interoperability-peps/issues/17
