### ISSUE TITLE
PEP 458: Consider mentioning Yubikeys for offline key management

### ISSUE THREAD

**Issue by ncoghlan** [pypa/interoperability-peps#24]
A separate discussion reminded me that one good way to address the "offline key management is hard" problem is through appropriate use of physical tokens like https://www.yubico.com/products/yubikey-hardware/

Yubico also publish a lot of open source code for working with their tokens, including Python libraries: https://github.com/Yubico

On a related note, if we pursue 2FA as a component of the security management of key updates, then Fedora/Red Hat's FreeOTP is an open source soft-token option: https://fedorahosted.org/freeotp/

**Comment by vladimir-v-diaz** [comment]
@dstufft 
Would you be interested in using Yubikey for off-pypi key management?  I can update PEP 458 to mention Yubikey and/or RECOMMENDED security tokens.

Also, let me know when you expect (approximate timeline) to begin reviewing PEP 458.  If you are busy, I can request for one of the other PEP editors to review & merge the pending pull requests in the meantime.

**Comment by vladimir-v-diaz** [comment]
Discussion on security tokens added in PR #26.
