### ISSUE TITLE
PEP 440: clarify local version identifiers can be used when running directly from VCS

### ISSUE THREAD

**Issue by ncoghlan** [pypa/interoperability-peps#25]
Folks are tying themselves in knots trying to avoid using local version identifiers to hold DVCS hashes when running from a source checkout: https://github.com/pydata/pandas/issues/9518

The restriction against upstream projects using local versions specifically relates to *published* releases that need to compared against version specifiers. There's no problem with using them when running from a source checkout, since that usually doesn't interact at all with the version specifier system (you're using the VCS URL to find the release in that case), and when it does (e.g. checking the base version at runtime), then the "release + additional patches" semantics of local version identifiers suits the situation perfectly.

That's currently not clear in the PEP, since it doesn't currently cover identification of unreleased versions at all. I don't have a specific wording change to propose as yet, but it will be along the lines of "upstream projects may also use local versions to differentiate unreleased software from the previous release".

**Comment by ncoghlan** [comment]
Reworded in https://hg.python.org/peps/rev/bf4ffb364faf to add a MAY for local versioning of local upstream builds.

**Comment by shoyer** [comment]
Thanks @ncoghlan, this looks great.
