### ISSUE TITLE
Idea: split environment markers out to their own PEP

### ISSUE THREAD

**Issue by ncoghlan** [pypa/interoperability-peps#28]
https://github.com/pypa/packaging-problems/issues/63 was just filed regarding the idea of making dependencies optional based on Python version.

It occurs to me that the environment markers section of PEP 426 (https://www.python.org/dev/peps/pep-0426/#environment-markers) might benefit from the PEP 440 treatment of being split out into its own PEP.

That should be much easier to standardise than the whole of PEP 426, and would be useful in its own right since pip, setuptools and other tools could adopt it as a component of their existing dependency specification syntax.

**Comment by qwcode** [comment]
btw, this idea is in motion...   PEP 496 is the new independent environment markers PEP, although PEP 426 still currently holds the old markers section

**Comment by ncoghlan** [comment]
PEP 508 now covers both extras and environment markers: https://www.python.org/dev/peps/pep-0508/

Flagging this as PEP 426, since the duplicated info still needs to be removed (also /cc @rbtcollins)

**Comment by ncoghlan** [comment]
The corresponding changes have been made to PEP 426: https://github.com/python/peps/commit/8ae8b612d4ea8b3bf5d8a7b795ae8aec48bbb7a3
