### ISSUE TITLE
OS X has different compatability semantics

### ISSUE THREAD

**Issue by qwcode** [pypa/interoperability-peps#36]
See https://github.com/pypa/pip/pull/1465

The wheel spec should account for this.

---

migrated from https://bitbucket.org/pypa/pypi-metadata-formats/issues/43/os-x-has-different-compatability-semantics

**Comment by pradyunsg** [comment]
Is this still relevant?

**Comment by ncoghlan** [comment]
The general problem of "How to identify potentially compatible wheels for the current system" does still exist, but the specifics of OS X on that front doesn't need its own issue.
