### ISSUE TITLE
Standard setup.py interface

### ISSUE THREAD

**Issue by qwcode** [pypa/interoperability-peps#51]
Step 1 in decoupling the process of building an sdist from setuptools/distutils is to standardise the setup.py interface so it is easier to create a custom shim that maps the setuptools invocation interface to a different build tool (d2to1 is a reasonable example of such a tool).

Not a blocker for metadata 2.0, but a key part of the next phase of decoupling distribution of Python software from distutils and setuptools.

---

migrated from https://bitbucket.org/pypa/pypi-metadata-formats/issues/24/standard-setuppy-interface

**Comment by pradyunsg** [comment]
This can be closed given PEP 517.

**Comment by ncoghlan** [comment]
Indeed!
