### ISSUE TITLE
Require issue references for changes to Provisional PEPs?

### ISSUE THREAD

**Issue by ncoghlan** [pypa/interoperability-peps#7]
Currently the new change log in PEP 440 links directly to the relevant discussion threads on distutils-sig.

That can work - we'd just follow up on those threads with a reference back to the issues here, so the linkage would be in place.

Another alternative would be to change the PEP references to point directly at the issue tracker, and then add the thread references here.

And the final (and my currently preferred option) would be to keep the direct references to the discussion thread archives, but also *add* references to the PEPs.

(Whatever we decide to do here is what I'll propose as a normative references for the PEP 1 change proposal).

**Comment by dstufft** [comment]
I don't have a major opinion either way, except that I trust the distutils-sig links to continue working for a lot longer then I trust Github links to work for... but I don't think it's a major big deal either way.

**Comment by ncoghlan** [comment]
Yeah, link stability is one of the major benefits of referring to the mailing list archives rather than a third party issue tracker.

Since I'm not inclined to set up a link redirector to provide stable links to PEP issues, lets leave this as is for now.
